# _Introduction_


Import data from citi bike portal for all the stations

The data could have been downloaded from links directly, but I downloaded the zip file as i noticed some discripencies in the file where there were more than on csv (one of them was dated). 

downloaded all the zip files for over 3 years to explore the usage before and after covid.
2019 : 12 months
2020 : 12 months ( April 2020 - covid) 
2021 : 12 months
2022 : 02 months

In [1]:
import pandas as pd
from pandas import to_datetime
import seaborn as sns
import matplotlib.pyplot as plt
import requests
import zipfile

2020

In [2]:
df_202001 = pd.read_csv("data\\202001-citibike-tripdata.csv.zip")
df_202002 = pd.read_csv("data\\202002-citibike-tripdata.csv.zip")
df_202003 = pd.read_csv("data\\202003-citibike-tripdata.csv.zip")
df_202004 = pd.read_csv("data\\202004-citibike-tripdata.csv.zip")

In [3]:
df_202005 = pd.read_csv("data\\202005-citibike-tripdata.csv.zip")
df_202006 = pd.read_csv("data\\202006-citibike-tripdata.csv.zip")
df_202007 = pd.read_csv("data\\202007-citibike-tripdata.csv.zip")

In [4]:
df_202008 = pd.read_csv("data\\202008-citibike-tripdata.csv.zip")
df_202009 = pd.read_csv("data\\202009-citibike-tripdata.csv.zip")
df_202010 = pd.read_csv("data\\202010-citibike-tripdata.csv.zip")
df_202011 = pd.read_csv("data\\202011-citibike-tripdata.csv.zip")
df_202012 = pd.read_csv("data\\202012-citibike-tripdata.csv.zip")

2021/22

df_202101 = pd.read_csv("data\\202101-citibike-tripdata.csv.zip", low_memory=False)

df_202102 = pd.read_csv("data\\202102-citibike-tripdata.csv.zip", low_memory=False)
df_202103 = pd.read_csv("data\\202103-citibike-tripdata.csv.zip", low_memory=False)
df_202104 = pd.read_csv("data\\202104-citibike-tripdata.csv.zip", low_memory=False)

df_202105 = pd.read_csv("data\\202105-citibike-tripdata.csv.zip", low_memory=False)
df_202106 = pd.read_csv("data\\202106-citibike-tripdata.csv.zip", low_memory=False)

df_202107 = pd.read_csv("data\\202107-citibike-tripdata.csv.zip", low_memory=False)
df_202108 = pd.read_csv("data\\202108-citibike-tripdata.csv.zip", low_memory=False)
df_202109 = pd.read_csv("data\\202109-citibike-tripdata.csv.zip", low_memory=False)

df_202110 = pd.read_csv("data\\202110-citibike-tripdata.csv.zip", low_memory=False)
df_202111 = pd.read_csv("data\\202111-citibike-tripdata.csv.zip", low_memory=False)
df_202112 = pd.read_csv("data\\202112-citibike-tripdata.csv.zip", low_memory=False)
df_202201 = pd.read_csv("data\\202201-citibike-tripdata.csv.zip", low_memory=False)

In [ ]:
#2019 for x in range 
print('done')
df_202102.info()

In [ ]:
df_202101.info()

In [6]:
#df_202102
df_202102 = df.rename(columns={'started_at': 'starttime', 'ended_at': 'stoptime'})

NameError: name 'df' is not defined

Concatinating the data frames before working on them

In [29]:
df02 = pd.DataFrame()
#frames = [df_202001,df_202002,df_202003,df_202004,df_202005,df_202006,df_202007,df_202008,df_202009,df_202010,df_202011,df_202012,df_202101,df_202102,df_202103,df_202104,df_202105,df_202106,df_202107,df_202108,df_202109,df_202110,df_202111,df_202112,df_202201]
frames = [df_202001,df_202002,df_202003,df_202004,df_202005,df_202006,df_202007,df_202008,df_202009,df_202010,df_202011,df_202012]
df02 = pd.concat(frames)

In [30]:
#tableau analysis data 
dfviz = [df_202001,df_202002,df_202003,df_202004,df_202005,df_202006,df_202007,df_202008,df_202009,df_202010,df_202011,df_202012]

In [31]:
df_viz = pd.concat(dfviz)

In [32]:
df_viz.tail(20)

,tripduration,starttime,stoptime,start station id,start station name,start station latitude,start station longitude,end station id,end station name,end station latitude,end station longitude,bikeid,usertype,birth year,gender
1088909,148,2020-12-31 23:55:42.2030,2020-12-31 23:58:10.4400,464,E 56 St & 3 Ave,40.759345,-73.967597,456,E 53 St & Madison Ave,40.759711,-73.974023,36946,Subscriber,1994,1
1088910,76,2020-12-31 23:56:20.4840,2020-12-31 23:57:37.2340,312,Allen St & Stanton St,40.722055,-73.989111,265,Stanton St & Chrystie St,40.722293,-73.991475,40896,Subscriber,1994,2
1088911,1504,2020-12-31 23:56:28.5940,2021-01-01 00:21:33.2290,3628,Lenox Ave & W 117 St,40.802557,-73.949078,3137,5 Ave & E 72 St,40.772828,-73.966853,37804,Subscriber,1984,0
1088912,268,2020-12-31 23:56:35.5290,2021-01-01 00:01:03.8460,4099,E 169 St & Webster Ave,40.834015,-73.908863,4177,Prospect Ave & Jennings St,40.831762,-73.896853,47843,Customer,1993,2
1088913,636,2020-12-31 23:56:52.5540,2021-01-01 00:07:28.8400,3143,5 Ave & E 78 St,40.776321,-73.964274,3142,1 Ave & E 62 St,40.761227,-73.960940,40691,Subscriber,1976,1
1088914,1124,2020-12-31 23:57:15.6080,2021-01-01 00:15:59.8620,490,8 Ave & W 33 St,40.751551,-73.993934,490,8 Ave & W 33 St,40.751551,-73.993934,45654,Subscriber,1998,1
1088915,369,2020-12-31 23:57:17.1180,2021-01-01 00:03:27.1140,3288,E 88 St & 1 Ave,40.778301,-73.948813,3282,5 Ave & E 88 St,40.783070,-73.959390,49620,Customer,1969,0
1088916,1060,2020-12-31 23:57:23.8780,2021-01-01 00:15:04.4860,3977,Prospect Ave & Longwood Ave,40.818990,-73.902020,3977,Prospect Ave & Longwood Ave,40.818990,-73.902020,45758,Subscriber,1989,1
1088917,184,2020-12-31 23:57:33.1060,2021-01-01 00:00:37.6170,372,Franklin Ave & Myrtle Ave,40.694546,-73.958014,364,Lafayette Ave & Classon Ave,40.689004,-73.960239,37243,Subscriber,1994,1
1088918,1970,2020-12-31 23:57:47.3580,2021-01-01 00:30:38.0560,3169,Riverside Dr & W 82 St,40.787209,-73.981281,529,W 42 St & 8 Ave,40.757570,-73.990985,45168,Subscriber,2001,1
1088919,519,2020-12-31 23:57:50.2000,2021-01-01 00:06:29.6850,265,Stanton St & Chrystie St,40.722293,-73.991475,307,Canal St & Rutgers St,40.714275,-73.989900,45215,Subscriber,1994,2
1088920,733,2020-12-31 23:58:10.1570,2021-01-01 00:10:23.5950,3143,5 Ave & E 78 St,40.776321,-73.964274,3374,Central Park North & Adam Clayton Powell Blvd,40.799484,-73.955613,44238,Subscriber,1973,1
1088921,1178,2020-12-31 23:58:14.1000,2021-01-01 00:17:52.3380,3335,Union St & 4 Ave,40.677274,-73.982820,3860,Wilson Ave & Troutman St,40.701660,-73.927540,47991,Customer,1988,1
1088922,1344,2020-12-31 23:58:17.4800,2021-01-01 00:20:41.6070,456,E 53 St & Madison Ave,40.759711,-73.974023,468,Broadway & W 56 St,40.765265,-73.981923,36946,Subscriber,1994,1
1088923,589,2020-12-31 23:58:21.2620,2021-01-01 00:08:10.9220,3999,Adam Clayton Powell Blvd & W 138 St,40.816960,-73.942296,3518,Lenox Ave & W 126 St,40.808442,-73.945209,48973,Subscriber,1997,1
1088924,2045,2020-12-31 23:58:21.7040,2021-01-01 00:32:27.1570,526,E 33 St & 5 Ave,40.747659,-73.984907,3614,Crescent St & 30 Ave,40.768692,-73.924957,36467,Subscriber,1994,1
1088925,288,2020-12-31 23:58:37.8400,2021-01-01 00:03:26.3250,3307,West End Ave & W 94 St,40.794165,-73.974124,3383,Cathedral Pkwy & Broadway,40.804213,-73.966991,47749,Subscriber,1969,0
1088926,152,2020-12-31 23:58:52.8090,2021-01-01 00:01:25.6720,3510,Adam Clayton Powell Blvd & W 123 St,40.807832,-73.949373,3518,Lenox Ave & W 126 St,40.808442,-73.945209,48691,Customer,1969,0
1088927,654,2020-12-31 23:59:55.9550,2021-01-01 00:10:50.6050,4073,W 51 St & Rockefeller Plaza,40.759700,-73.978082,500,Broadway & W 51 St,40.762288,-73.983362,49564,Subscriber,1994,1
1088928,2589,2020-12-31 23:59:57.4070,2021-01-01 00:43:06.4490,3581,Underhill Ave & Lincoln Pl,40.674012,-73.967146,3581,Underhill Ave & Lincoln Pl,40.674012,-73.967146,47364,Customer,1969,0

In [45]:
df_viz.to_csv('df_01_2020_12_2020.csv', index=False)

In [34]:
df_viz[df_viz['birth year'] < 1930]

,tripduration,starttime,stoptime,start station id,start station name,start station latitude,start station longitude,end station id,end station name,end station latitude,end station longitude,bikeid,usertype,birth year,gender
351,439,2020-01-01 00:45:06.0630,2020-01-01 00:52:25.9720,3711,E 13 St & Avenue A,40.729667,-73.980680,439,E 4 St & 2 Ave,40.726281,-73.989780,30452,Subscriber,1896,2
1599,278,2020-01-01 02:56:11.5060,2020-01-01 03:00:49.9680,489,10 Ave & W 28 St,40.750664,-74.001768,453,W 22 St & 8 Ave,40.744751,-73.999154,40893,Subscriber,1888,1
5278,463,2020-01-01 12:00:43.6230,2020-01-01 12:08:26.7460,3574,Prospect Pl & Underhill Ave,40.676969,-73.965790,83,Atlantic Ave & Fort Greene Pl,40.683826,-73.976323,21416,Subscriber,1893,2
5283,382,2020-01-01 12:01:11.1700,2020-01-01 12:07:33.4770,3739,Perry St & Greenwich Ave,40.735918,-74.000939,435,W 21 St & 6 Ave,40.741740,-73.994156,32418,Subscriber,1900,1
5881,1748,2020-01-01 12:27:41.9800,2020-01-01 12:56:50.7850,3383,Cathedral Pkwy & Broadway,40.804213,-73.966991,514,12 Ave & W 40 St,40.760875,-74.002777,41209,Subscriber,1919,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1083792,92,2020-12-31 18:34:28.5360,2020-12-31 18:36:00.7590,2003,1 Ave & E 18 St,40.733812,-73.980544,545,E 23 St & 1 Ave,40.736502,-73.978095,39303,Subscriber,1900,1
1083842,93,2020-12-31 18:36:09.6270,2020-12-31 18:37:43.4440,545,E 23 St & 1 Ave,40.736502,-73.978095,2012,E 27 St & 1 Ave,40.739445,-73.976806,39303,Subscriber,1900,1
1085406,248,2020-12-31 19:34:49.7110,2020-12-31 19:38:58.1110,268,Howard St & Centre St,40.719105,-73.999733,250,Lafayette St & Jersey St,40.724561,-73.995653,41360,Subscriber,1900,2
1086563,120,2020-12-31 20:32:12.6040,2020-12-31 20:34:12.7700,250,Lafayette St & Jersey St,40.724561,-73.995653,151,Cleveland Pl & Spring St,40.722104,-73.997249,41360,Subscriber,1900,2
1087049,328,2020-12-31 21:07:40.8750,2020-12-31 21:13:08.9250,368,Carmine St & 6 Ave,40.730386,-74.002150,251,Mott St & Prince St,40.723180,-73.994800,37406,Subscriber,1918,1

In [35]:
df_viz.shape

(19506857, 15)

In [24]:
df_viz[df_viz['gender']==1].count()

tripduration               12513016
starttime                  12513016
stoptime                   12513016
start station id           12513016
start station name         12513016
start station latitude     12513016
start station longitude    12513016
end station id             12513016
end station name           12513016
end station latitude       12513016
end station longitude      12513016
bikeid                     12513016
usertype                   12513016
birth year                 12513016
gender                     12513016
dtype: int64

In [28]:
df_viz['gender'].unique()

array([1, 0, 2], dtype=int64)

df_actual = [df_202101,df_202102,df_202103,df_202104]
df_actual = pd.concat(df_actual)
df_actual.to_csv('df_012021_042021.csv', index=False)
df_actual.tail()
seriesactual= df_actual.ride_id.groupby(pd.to_datetime(df_actual.started_at).dt.strftime('%Y-%m-%d %H')).count()
dfact = pd.DataFrame({'date': seriesactual.index, 'count': seriesactual.values})
dfact.tail()
dfact.to_csv('timeseriesdata_actualtocompare.csv', index=False)

In [39]:
df02.starttime

0          2020-01-01 00:00:55.3900
1          2020-01-01 00:01:08.1020
2          2020-01-01 00:01:42.1400
3          2020-01-01 00:01:45.5610
4          2020-01-01 00:01:45.7880
                     ...
1088924    2020-12-31 23:58:21.7040
1088925    2020-12-31 23:58:37.8400
1088926    2020-12-31 23:58:52.8090
1088927    2020-12-31 23:59:55.9550
1088928    2020-12-31 23:59:57.4070
Name: starttime, Length: 19506857, dtype: object

## Hourly

In [40]:
#series = df02.usertype.groupby((pd.to_datetime(df02.starttime).dt.hour)).count()
series1 = df02.usertype.groupby(pd.to_datetime(df02.starttime).dt.strftime('%Y-%m-%d %H')).count()
#df['hour-date'] = df02.starttime, format='%Y-%m-%d %H').sum()

In [41]:
df = pd.DataFrame({'date': series1.index, 'count': series1.values})
df.head()

            date  count
0  2020-01-01 00    509
1  2020-01-01 01    633
2  2020-01-01 02    482
3  2020-01-01 03    260
4  2020-01-01 04    137

In [42]:
df.to_csv('timeseriesdata.csv', index=False)

## Daily for weather

In [46]:
series2  = df02.usertype.groupby(pd.to_datetime(df02.starttime).dt.strftime('%Y-%m-%d')).count()
dfmonth = pd.DataFrame({'date': series2.index, 'count': series2.values})
dfmonth.to_csv('timeseriesdatamonth.csv', index=False)
dfmonth.head()

         date  count
0  2020-01-01  18114
1  2020-01-02  41556
2  2020-01-03  31873
3  2020-01-04  29436
4  2020-01-05  27589

In [47]:
dfmonth.shape

(366, 2)

# Prepare Data - 201901

### error 
datatoexcel = pd.ExcelWriter('finaldata.xlsx') #write DataFrame to excel
df.to_excel(datatoexcel) # save the excel
datatoexcel.save()

### Renaming the features

In [ ]:
df02['starttime'] = pd.to_datetime(df02['starttime'])
df02['stoptime'] = pd.to_datetime(df02['stoptime'])
df02['start_hour'] = df02['starttime'].dt.hour.astype('category')
df02['start_day'] = df02['starttime'].dt.day.astype('category')

df['weekday'] = df['starttime'].dt.weekday.astype('category')
df['weekend'] = [ d >=5 for d in df['weekday']]
df.weekday.unique()

In [ ]:
df.weekend.unique()
df.starttime.unique()

In [ ]:
df02.resample('H', on='starttime')

In [ ]:
df['start station id'].head()

Converting

In [ ]:
cols = ['start station name', 'end station name', 'bikeid', 'usertype', 'gender']
for col in cols:
    df[col] = df[col].astype('category')

In [ ]:
df.info()

In [ ]:
df1 = pd.DataFrame()
df1['tripminutes'] = df['tripduration'] // 60
#sns.displot(data=df1,x="tripminutes", bins=range(1,61), aspect=10/5)
#sns.countplot(data=df, x="start_hour")

In [ ]:
per_hour = pd.value_counts(df['start_hour'])
rph_df = per_hour.to_frame()
rph_df.reset_index(inplace=True)
rph_df.rename(columns = {'index' : 'time', 'start_hour' : 'rides'},inplace=True)


dfts = df.groupby(["start_hour", "start_hour"]).size().reset_index(name="Time")

In [ ]:
df.tail()

In [ ]:
tsdf = pd.DataFrame()
tsdf = df.assign(Date=df.starttime.dt.round('H'))

In [ ]:
df_202105.info()

In [ ]:
df_202201.info()